plugins:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      file-lines:
        enabled: false
      method-lines:
        enabled: false
      comma-dangle:
        enabled: false
      linebreak-style:
        enabled: false
      import/extensions:
        enabled: false
      file-lines:
        enabled: false
      similar-code:
        enabled: false
      identical-code:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "server/**/*.js"
  - "client/**/*.js"
  - "client/**/*.jsx"

exclude_patterns:
  - "webpack.config.*.js"
  - "node_modules/"
  - "client/src/__tests__/__mocks__/"
  - "template/*"
  - "server/__test__"
  - "client/src/__tests__"
  - "server/migrations"
  - "server/models"
  - "server/seeders"
