language: node_js
node_js: 
   -  "8.9.1"
services:
  - postgresql
env:
  global:
    - NODE_ENV=test
    - CC_TEST_REPORTER_ID=bee56f01164981a59f4a6d15b0bbff8b4b49953b954c700532edc7471d2036e7
before_script:
  - psql -c 'create database recipes_testing_db;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - npm install sequelize
  - npm install cross-env
  - npm install sequelize-cli
  - npm install pg
  - npm install pg-hstore
  - npm install nyc
script:
  - npm run test

after_success:
  - npm run coverage

  