language: node_js
node_js: 
   -  "8.9.1"
services:
  - postgresql
before_script:
  - psql -c 'create database recipes_testing_db;' -U postgres 
install:
  - npm install sequelize
  - npm install sequelize-cli
  - npm install pg
  - npm install pg-hstore
  - npm install nyc
script:
  - sequelize db:migrate --env test
  - npm run coveralls
  