language: node_js
node_js: 
   -  "6.11.2"
services:
  - postgresql
before_script:
  - psql -c 'CREATE ROLE bill with CREATEDB;'
  - psql -c 'create database more_recipes_test;' -U bill 
install:
  - npm install sequelize
  - npm install sequelize-cli
  - npm install pg
  - npm install pg-hstore
script:
  - sequelize db:migrate --env test