export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_INFORMATION = 'GET_USER_INFORMATION';

export const ADD_RECIPE_REQUEST = 'ADD_RECIPE_REQUEST';
export const ADD_RECIPE = 'ADD_RECIPE';

export const GET_RECIPES_REQUEST = 'GET_RECIPES_REQUEST';
export const GET_RECIPES = 'GET_RECIPES';

export const GET_ONE_RECIPE_REQUEST = 'GET_ONE_RECIPE_REQUEST';
export const GET_ONE_RECIPE = 'GET_ONE_RECIPE';

export const GET_USER_RECIPES_REQUEST = 'GET_USER_RECIPES_REQUEST';
export const GET_USER_RECIPES = 'GET_USER_RECIPES';

export const ADD_FAVORITE_RECIPE = 'ADD_FAVORITE_RECIPE';
export const FETCH_FAVORITE_RECIPES = 'FETCH_FAVORITE_RECIPES';

export const EDIT_RECIPE_REQUEST = 'EDIT_RECIPE_REQUEST';
export const EDIT_RECIPE = 'EDIT_RECIPE';

export const REMOVE_RECIPE_REQUEST = 'REMOVE_RECIPE_REQUEST';
export const REMOVE_RECIPE = 'REMOVE_RECIPE';

export const ADD_REVIEW_REQUEST = 'ADD_REVIEW_REQUEST';
export const ADD_REVIEW = 'ADD_REVIEW';

export const UPVOTE_RECIPE = 'UPVOTE_RECIPE';
export const DOWNVOTE_RECIPE = 'DOWNVOTE_RECIPE';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const SEARCH_RECIPES = 'SEARCH_RECIPES';
export const POPULAR_RECIPES = 'POPULAR_RECIPES';
